steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/flask-web-app-tutorial', '.']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: 
      - 'run'
      - 'deploy'
      - 'flask-web-app-tutorial'
      - '--image'
      - 'gcr.io/$PROJECT_ID/flask-web-app-tutorial'
      - '--platform'
      - 'managed'
      - '--region'
      - 'us-central1'
      - '--memory'
      - '512Mi'
      - '--timeout'
      - '300'
images:
  - 'gcr.io/$PROJECT_ID/flask-web-app-tutorial'