steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/flask-web-app-tutorial', '-f', 'dockerfile', '.']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'flask-web-app-tutorial', '--image', 'gcr.io/$PROJECT_ID/flask-web-app-tutorial', '--platform', 'managed', '--region', 'us-central1']
images:
  - 'gcr.io/$PROJECT_ID/flask-web-app-tutorial'
